# Sample .travis.yml for R projects

language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

r_github_packages:
  - HenrikBengtsson/devtools@hotfix/parse_deps

branches:
  only:
    - master

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
