language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

branches:
  only:
    - master
    - cran
    - /^hotfix\/.*$/
    - /^release\/.*$/

r_github_packages:		
  - hadley/devtools@1302fef

r_packages:
  - covr
  - Hmisc

after_success:
  - Rscript -e 'library(covr); codecov()'
