# Sample .travis.yml for R projects

language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

r_github_packages:
  - hadley/devtools
  - cran/survival

branches:
  only:
    - master
    - devel
    - /^hotfix\/.*$/
    - /^release\/.*$/

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
