#' Define a Markov Model
#'
#' Combine information on parameters, transition matrix and
#' states defined through [define_parameters()],
#' [define_transition()] and
#' [define_state()] respectively.
#'
#' This function checks whether the objects are compatible
#' in the same model (same state names...).
#'
#' State values and transition probabilities referencing
#' `state_time` are automatically expanded to implicit
#' tunnel states.
#'
#' @param transition An object generated by
#'   [define_transition()].
#' @param ... Object generated by
#'   [define_state()].
#' @param states List of states, only used by
#'   `define_strategy_`` to avoid using `...`.
#' @param partitioned_survival Partitioned survival argument.
#'   See [survival_from_data()] and
#'   [partitioned_survival_from_tabular()].
#' @param strategy_name name of the strategy, may be used in parameters.
#' @param transition_matrix Deprecated argument, use
#'   `transition`.
#'
#' @return An object of class `uneval_model`` (a list
#'   containing the unevaluated parameters, matrix and
#'   states).
#'
#' @export
#'
#' @example inst/examples/example_define_strategy.R
define_strategy <- function(...,
                            transition = define_transition(),
                            transition_matrix = NULL,
                            strategy_name = NULL) {
  if (!is.null(transition_matrix)) {
    warning("Argument 'transition_matrix' is deprecated, use 'transition' instead.")
    transition <- transition_matrix
  }
  
  states <- define_state_list_(list(...))
  
  define_strategy_(transition = transition,
                   states = states,
                   strategy_name = strategy_name)
}

#' @rdname define_strategy
#' @export
define_strategy_ <- function(transition,
                             states,
                             partitioned_survival = NULL,
                             strategy_name = NULL) {
  if (inherits(transition, "uneval_matrix")) {
    if (!get_state_number(states) == get_matrix_order(transition)) {
      stop(
        sprintf(
          "Number of state in model input (%i) differ from number of state in transition object (%i).",
          get_state_number(states),
          length(get_state_names(transition))
        )
      )
    }
    
    if (!identical(as.vector(sort(get_state_names(states))),
                   as.vector(sort(get_state_names(transition))))) {
      stop("State names differ from transition object.")
    }
  }
  
  structure(
    list(
      transition = transition,
      states = states,
      partitioned_survival = partitioned_survival,
      strategy_name = strategy_name
    ),
    class = "uneval_model"
  )
}

#' Get Markov Model Transition Matrix
#'
#' Works on both unevaluated and evaluated models.
#'
#' @param x An `uneval_model` or `eval_model` object.
#'
#' @return An `uneval_matrix` or `uneval_matrix` object.
#'
#' @keywords internal
get_transition <- function(x, ...) {
  UseMethod("get_transition")
}

get_transition.default <- function(x, ...) {
  x$transition
}

get_transition.uneval_model <-
  function(uneval_model, transition_options){
    this_transition <- NULL
    if(inherits(uneval_model$transition, "uneval_matrix"))
      this_transition <- uneval_model$transition
    if(inherits(uneval_model$transition, "part_surv"))
      this_transition <- uneval_model$transition
    if(inherits(uneval_model$transition, "character") & 
       inherits(uneval_model$partitioned_survival, "part_surv"))
      this_transition <- uneval_model$partitioned_survival
    if(is.null(this_transition))
      stop("can't find a valid transition")
    
    if(!missing(transition_options)){
      this_transition <- modify_transition(this_transition, transition_options)
    }
    this_transition
  }

set_transition <- function(x, m) {
  UseMethod("set_transition")
}

set_transition.default <- function(x, m) {
  x$transition <- m
  x
}

get_states <- function(x){
  UseMethod("get_states")
}

get_states.default <- function(x) {
  x$states
}

set_states <- function(x, s) {
  UseMethod("set_states")
}

set_states.default <- function(x, s) {
  x$states <- s
  x
}

get_state_value_names.uneval_model <- function(x) {
  get_state_value_names(get_states(x))
}

get_state_names.uneval_model <- function(x, ...) {
  get_state_names(get_states(x))
}

get_partitioned_survival <- function(x) {
  UseMethod("get_partitioned_survival")
}
get_partitioned_survival.default <- function(x) {
  x$partitioned_survival
}
